### Get indices
GET localhost:9200/_cat/indices

### Get all mapping
GET http://localhost:9200/jaeger-main-jaeger-span-2025-03-28/_mapping
Content-Type: application/json

### Get all spans
GET http://localhost:9200/jaeger-main-jaeger-span-2025-03-30/_search
Content-Type: application/json

### Get all services
POST http://localhost:9200/jaeger-main-jaeger-service-2025-03-28/_search
Content-Type: application/json

{
  "size": 100
}

### Apply index level setting
PUT http://localhost:9200/_settings
Content-Type: application/json

{
  "index.search.slowlog.threshold.query.warn": "0ms",
  "index.search.slowlog.threshold.query.info": "0ms",
  "index.search.slowlog.threshold.query.debug": "0ms",
  "index.search.slowlog.threshold.query.trace": "0ms"
}

### Get list of services
POST http://localhost:9200/jaeger-main-jaeger-service-2025-03-28/_search
Content-Type: application/json

{
  "size": 0,
  "track_total_hits": 2147483647,
  "aggregations": {
    "distinct_services": {
      "terms": {
        "field": "serviceName",
        "size": 10000,
        "min_doc_count": 1,
        "shard_min_doc_count": 0,
        "show_term_doc_count_error": false,
        "order": [
          {
            "_count": "desc"
          },
          {
            "_key": "asc"
          }
        ]
      }
    }
  }
}

### Get spans for trace id
POST http://localhost:9200/jaeger-main-jaeger-span-2025-03-28/_search
Content-Type: application/json

{
  "size": 10000,
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "traceID": {
              "value": "62e13a0d44b87c195a17d5f54d414e73"
            }
          }
        }
      ],
      "boost": 1.0
    }
  },
  "sort": [
    {
      "startTime": {
        "order": "asc"
      }
    }
  ],
  "track_total_hits": 2147483647,
  "search_after": [1742924873404035]
}

### Test GetLatencies
GET http://localhost:9200/jaeger-main-jaeger-span-2025-03-30/_search
Content-Type: application/json

{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {"term": {"process.serviceName": "redis"}},
        {
          "range": {
            "startTimeMillis": {
              "gte": 1743351287470,
              "lte": 1743354887470 }}}]}},
  "aggs": {
    "operations": {
      "terms": {"field": "operationName"},
      "aggs": {
        "latency": {
          "percentiles": {"field": "duration", "percents": [95]}}}}}
}

### Example ES query for callRate with groupByOperation=true over one hour range:
GET http://localhost:9200/jaeger-main-jaeger-span-2025-03-30/_search
Content-Type: application/json

{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {"term": {"process.serviceName": "frontend"}},
        {
          "range": {
            "startTimeMillis": {
              "gte": 1743358979071,
              "lte": 1743362579071}}}, {
          "nested": {
            "path": "tags",
            "query": {
              "bool": {
                "must": [
                  {"term": {"tags.key": "span.kind"}},
                  {"term": {"tags.value": "server"}}]}}}}]}},
  "aggs": {
    "operations": {
      "terms": {"field": "operationName"},
      "aggs": {
        "total_call_count": {"value_count": {"field": "spanID"}},
        "call_rate_per_second": {
          "bucket_script": {
            "buckets_path": {"count": "total_call_count"},
            "script": "params.count / 3600.0" }}}}}
}

### Example ES query for callRate with 1-minute buckets over one hour range:
GET http://localhost:9200/jaeger-main-jaeger-span-2025-03-30/_search
Content-Type: application/json

{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {"term": {"process.serviceName": "frontend"}},
        {
          "range": {
            "startTimeMillis": {
              "gte": 1743358979071,
              "lte": 1743362579071}}}, {
          "nested": {
            "path": "tags",
            "query": {
              "bool": {
                "must": [
                  {"term": {"tags.key": "span.kind"}},
                  {"term": {"tags.value": "server"}}]}}}}]}},
  "aggs": {
    "over_time": {
      "date_histogram": {
        "field": "startTimeMillis",
        "fixed_interval": "1m"
      },
      "aggs": {
        "total_call_count": {"value_count": {"field": "spanID"}},
        "call_rate_per_second": {
          "bucket_script": {
            "buckets_path": {"count": "total_call_count"},
            "script": "params.count / 60.0" }}}}}
}

### Test Error rate
GET http://localhost:9200/jaeger-main-jaeger-span-2025-03-30/_search
Content-Type: application/json

{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {"term": {"process.serviceName": "frontend"}},
        {
          "range": {
            "startTimeMillis": {
              "gte": 1743358979071,
              "lte": 1743362579071}}}, {
          "nested": {
            "path": "tags",
            "query": {
              "bool": {
                "must": [
                  {"term": {"tags.key": "span.kind"}},
                  {"term": {"tags.value": "client"}}]}}}}]}},
  "aggs": {
    "operations": {
      "terms": {"field": "operationName"},
      "aggs": {
        "error_spans": {
          "nested": { "path": "tags" },
          "aggs": {
            "filter_error_tag": {
              "filter": {
                "bool": {
                  "must": [
                    { "term": { "tags.key": "error" } },
                    { "term": { "tags.value": "true" } }]}}}}
        },
        "total_spans": {
          "value_count": { "field": "spanID" }
        },
        "error_rate": {
          "bucket_script": {
            "buckets_path": {
              "errors": "error_spans>filter_error_tag._count",
              "total": "total_spans.value"
            },
            "script": "params.total > 0 ? (params.errors / params.total * 100) : 0"}}}}}
}